"""add search_text

Revision ID: 1517221fd58b
Revises: f547082063f1
Create Date: 2026-06-13 10:52:45.801924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1517221fd58b'
down_revision: Union[str, Sequence[str], None] = 'f547082063f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('search_text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### command auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'search_text')
    # ### end Alembic commands ###
