services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: codehub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - codehub_network

  app:
    build: .
    ports:
      - "2002:2002"
      - "5678:5678"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:12345678@db:5432/codehub
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - codehub_network

volumes:
  db_data:

networks:
  codehub_network:
    driver: bridge
