"""edit file table

Revision ID: f547082063f1
Revises: 230dd196f8b4
Create Date: 2026-06-08 14:59:19.330972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f547082063f1'
down_revision: Union[str, Sequence[str], None] = '230dd196f8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('relative_path', sa.Text(), nullable=False))
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_column('files', 'relative_path')
    # ### end Alembic commands ###
