"""add is_active to livestream

Revision ID: c7c02b3916c8
Revises: a8611a6e678e
Create Date: 2026-05-15 14:13:22.677307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c02b3916c8'
down_revision: Union[str, Sequence[str], None] = 'a8611a6e678e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestreams', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key('fk_livestream_current_question', 'livestreams', 'questions', ['current_question_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_livestream_current_question', 'livestreams', type_='foreignkey')
    op.drop_column('livestreams', 'is_active')
    # ### end Alembic commands ###
